name: bootstrapper
description: Bootstrapper is a package to initialize multiple config in parallel by grouping them. 
version: 0.1.0
repository: https://github.com/akurnaz/bootstrapper

environment:
  sdk: ^3.7.2

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
