name: bootstrapper
description: Bootstrapper is a package to initialize multiple config in parallel by grouping them. 
version: 0.1.0
repository: https://github.com/akurnaz/bootstrapper

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
